# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------
# pylint: disable=too-many-lines

from knack.help_files import helps

helps['fidalgo environment guided-create'] = """
    type: command
    short-summary: "Create an environment using guided prompts."
    examples:
      - name: Environments_CreateByCatalogItem
        text: |-
               az fidalgo environment create --name "{environmentName}"
      - name: Environments_CreateByTemplateUri
        text: |-
               az fidalgo environment create --name "{environmentName}"
"""
