# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------
# pylint: disable=too-many-statements
# pylint: disable=too-many-locals
# pylint: disable=bad-continuation
# pylint: disable=line-too-long

from azure.cli.core.commands import CliCommandType
from azext_fidalgo.generated._client_factory import (
    cf_environment,
)

fidalgo_environment = CliCommandType(
    operations_tmpl='azext_fidalgo.vendored_sdks.fidalgo.operations._environments_operations#EnvironmentsOperations.{}',
    client_factory=cf_environment,
)

def load_command_table(self, _):

    with self.command_group('fidalgo environment', fidalgo_environment, client_factory=cf_environment) as g:
        g.custom_command('list', 'fidalgo_environment_list')
        g.custom_show_command('show', 'fidalgo_environment_show')
        g.custom_command('create', 'fidalgo_environment_create', supports_no_wait=True)
        g.custom_command('guided-create', 'fidalgo_environment_guided_create', supports_no_wait=True)
        g.custom_command('update', 'fidalgo_environment_update', supports_no_wait=True)
        g.custom_command('delete', 'fidalgo_environment_delete', supports_no_wait=True, confirmation=True)
        g.custom_command('deploy', 'fidalgo_environment_deploy', supports_no_wait=True)
        g.custom_wait_command('wait', 'fidalgo_environment_show')

    with self.command_group('fidalgo', is_experimental=True):
        pass
